language: python
python:
  - "2.7"
  - "3.6"
stages:
  - check
  - test
install:
  - pip install -r requirements.txt
  - pip install ./
jobs:
  include:
    - stage: check
      script: ./runcheck
script: ./runtests
after_success:
  - codecov
