#!/usr/bin/env sh

# ==============================================================================
# Visual Studio Codium post install script
# ==============================================================================
# This script will do the following:
# 1. create a symlink of the install dir without a version number in the name
# 2. create a bin directory inside your user home
# 3. create a symlink of the code executable inside your user home bin dir called "vscode"
#
# WARNING: Any existing symlink will be remove to relink with current version of the software.
# ==============================================================================

# ==============================================================================
# arguments passed by packagerbuddy
# ==============================================================================
software="$1"
version="$2"

# ==============================================================================
# create version-less symlink
# ==============================================================================
link="$(dirname "$PWD")"/$1

# remove existing link
if [ \( -e $link \) ]
then
    rm $link
fi

ln -s $PWD $link

# ==============================================================================
# ensure user home bin exists
# ==============================================================================
usr_bin=~/bin

if [ ! \( -d $usr_bin \) ]
then
    mkdir $usr_bin
fi

# ==============================================================================
# create symlink to user home bin
# ==============================================================================
src_exec=$link/$software
dst_exec=$usr_bin/$software

if [ \( -e $dst_exec \) ]
then
    rm $dst_exec
fi

ln -s $src_exec $dst_exec
