#!/usr/bin/env sh

# =============================================================================
# Enviroment Modules post install script
# =============================================================================
# This script will do the following:
# 1. run the pre-compile configuration
# 2. compile the code
# 3. create a symlink of the compiled command lines to the system
#
# WARNING: Any existing symlink will be remove to relink with current version of the software.
# =============================================================================

# =============================================================================
# arguments passed by packagerbuddy
# =============================================================================
software="$1"
version="$2"

# =============================================================================
# create version-less symlink
# =============================================================================
link="$(dirname "$PWD")"/$1

# remove existing link
if [ \( -e $link \) ]
then
    rm $link
fi

ln -s $PWD $link

# =============================================================================
# run pre-compile configuration
# =============================================================================
cd $link
sudo ./configure > /dev/null 2>$1

# =============================================================================
# compile 
# =============================================================================
sudo make install > /dev/null 2>$1

# =============================================================================
# symlink CLI to system 
# =============================================================================
# profile.sh -> module.sh
src_module_sh=$link/"init/profile.sh"
dst_module_sh="/etc/profile.d/modules.sh"
if [ \( -e $dst_module_sh \) ]
then
    sudo rm $dst_module_sh
fi

sudo ln -s $src_module_sh $dst_module_sh

# profile.csh -> module.csh
src_module_csh=$link/"init/profile.csh"
dst_module_csh="/etc/profile.d/modules.csh"
if [ \( -e $dst_module_csh \) ]
then
    sudo rm $dst_module_csh
fi

sudo ln -s $src_module_csh $dst_module_csh
